// Automatically generated by gen.pl, don't edit #	<remove the line>


struct support_list {
	char *name;
	char *log_name;
	char *full_name;
	char *supp_name;
	char *supp_value;
	char *log_level;
};
extern struct support_list supports[];
#define SUPPORT_COUNT 31

/*edit by marcov______^^___original value: 29 
29
 1 + for telnet
 1 + for sshd
----
31 
*/